name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    uses:
      ./.github/workflows/pr.yml
  dockerize:
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses:
      ./.github/workflows/dockerize.yml

  local-deploy:
    needs: dockerize
    uses: ./.github/workflows/promote.yml
    with:
      environment: local
    secrets: inherit
