name: CI

on:
  push:
    branches:
      - main
  #temporary
  pull_request:
    branches:
      - main

jobs:
  build:
    uses:
      ./.github/workflows/pr.yml
  dockerize:
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses:
      ./.github/workflows/dockerize.yml
  ##
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  ##

  local-deploy:
    needs: dockerize
    uses: ./.github/workflows/promote.yml
    with:
      environment: local
    secrets: inherit
